#!/bin/bash

# -*- coding: utf-8 -*-
# author:oh

set -a

# config file with all path names and variables relevant for the directory

# filepath for main .pdf output. outpath variables contain outpaths for 
# all different cases specified in the LaTeXcompile.sh file and 
# corresponding to the different spec variables

# path for regular output
outpath=output/pdf

# path for auxillary files
auxpath=output/aux

# alternative paths for output files and their name conditions
altoutsnip=(CV Cover)
altoutsnippath=(output/pdf output/pdf)

# paths for copy files 
copypath=output/copy

# contitions for copying output
copycond=Cover

# path to main latex directory
latexpath=latex

# variable file name
variablepath=latex/variables.dat

set +a
